// Bump this whenever DEFAULT_STOPS / SEED_BOOKINGS change in a way that
// existing localStorage data should pick up (see useTrip.js migration)
export const ROUTE_VERSION = 6

export const ACTIVITIES = [
  {id:'nature',   label:'🏔️ Nature & Parks',   color:'#4ade80'},
  {id:'culture',  label:'🏛️ Culture & History', color:'#60a5fa'},
  {id:'food',     label:'🍜 Food & Drink',       color:'#f97316'},
  {id:'nightlife',label:'🎶 Nightlife',           color:'#c084fc'},
  {id:'roadtrip', label:'🛣️ Road Trip Stop',     color:'#facc15'},
  {id:'beach',    label:'🏖️ Beach',              color:'#22d3ee'},
  {id:'shopping', label:'🛍️ Shopping',           color:'#f472b6'},
  {id:'adventure',label:'🧗 Adventure',           color:'#fb923c'},
];

export const ACCOMM = [
  {id:'hotel',       label:'🏨 Hotel'},
  {id:'airbnb',      label:'🏠 Airbnb'},
  {id:'hostel',      label:'🛏️ Hostel'},
  {id:'camping',     label:'⛺ Camping'},
  {id:'motel',       label:'🚗 Motel'},
  {id:'friends',     label:'👥 Staying with friends'},
  {id:'decide_later',label:'🤷 Figure it out'},
];

export const DEFAULT_STOPS = [
  // ── PACIFIC COAST HIGHWAY ──
  {id:'d1',  name:'San Francisco, CA',                      lat:37.7749, lng:-122.4194, days:3, hours:0, accommodation:'friends', accommodationNotes:"Staying with Andreas's mom's boss — 5620 La Salle Avenue, San Francisco. Free accommodation!", budget_per_day:650, activities:['culture','food','nightlife'], notes:'Start of the trip! Golden Gate Bridge walk, Alcatraz, Mission burritos, Haight-Ashbury. Arriving Sep 21. Staying with Andreas\'s mom\'s boss at 5620 La Salle Avenue.', mustSee:['Golden Gate Bridge','Alcatraz','Fishermans Wharf','Mission District']},
  {id:'d6',  name:'Yosemite National Park, CA',             lat:37.8651, lng:-119.5383, days:2, hours:0, accommodation:'camping', accommodationNotes:'Book Curry Village or Yosemite Valley Lodge IMMEDIATELY — sells out months ahead. Or camp in the valley.', budget_per_day:715, activities:['nature','adventure'], notes:'Drive up from San Francisco via Highway 120 through the Central Valley (~3.5-4h) — Tioga Pass may still be open in mid-September for the high-country route. From here, head back toward the coast via Highway 99/152 to Monterey. September = perfect weather, fewer crowds than summer.', mustSee:['Yosemite Valley','Half Dome viewpoint','Yosemite Falls','Tunnel View','Mirror Lake']},
  {id:'d2',  name:'Monterey, CA',                           lat:36.6002, lng:-121.8947, days:1, hours:0, accommodation:'',        accommodationNotes:'', budget_per_day:780, activities:['nature','culture'], notes:'Drive down Highway 1 from SF — this IS the PCH. 17-Mile Drive, Cannery Row, sea otters at the aquarium', mustSee:['17-Mile Drive','Monterey Bay Aquarium','Carmel-by-the-Sea']},
  {id:'d3',  name:'Big Sur, CA',                            lat:36.2704, lng:-121.8081, days:0, hours:0, accommodation:'',        accommodationNotes:'', budget_per_day:0, activities:['nature','adventure'], notes:'Drive through on Sep 27 — no overnight stay. Most dramatic coastal scenery in the US. Bixby Bridge, McWay Falls, Pfeiffer Beach. Take it slow.', mustSee:['Bixby Creek Bridge','McWay Falls','Pfeiffer Beach','Julia Pfeiffer Burns State Park']},
  {id:'d4',  name:'San Luis Obispo, CA',                    lat:35.2828, lng:-120.6596, days:1, hours:0, accommodation:'',        accommodationNotes:'', budget_per_day:650, activities:['food','nightlife'], notes:'Great college town, great food scene. Last PCH stop before LA.', mustSee:['Bubblegum Alley','Madonna Inn','Downtown SLO']},
  {id:'d40', name:'Santa Barbara, CA',                      lat:34.4208, lng:-119.6982, days:1, hours:0, accommodation:'',        accommodationNotes:'', budget_per_day:780, activities:['beach','culture','food'], notes:'The "American Riviera" — Spanish colonial architecture, palm-lined State Street, and a relaxed beach town vibe. Great stop between SLO and LA.', mustSee:['Santa Barbara Mission','Stearns Wharf','State Street']},
  {id:'d5',  name:'Los Angeles, CA',                        lat:34.0522, lng:-118.2437, days:5, hours:0, accommodation:'airbnb', accommodationNotes:'Stay Silver Lake, Los Feliz or East Hollywood — central and cool', budget_per_day:975, activities:['culture','nightlife','food','shopping'], notes:'5 nights — enough time to really explore. Venice Beach, Griffith Observatory, Getty Museum, Silver Lake nightlife, a day in Santa Monica, one night in Hollywood.', mustSee:['Venice Beach','Griffith Observatory','Hollywood Sign','Getty Museum','Santa Monica Pier','Sunset Strip']},
  // ── CONTINUING SOUTH ──
  {id:'d7',  name:'San Diego, CA',                          lat:32.7157, lng:-117.1611, days:4, hours:0, accommodation:'',        accommodationNotes:'', budget_per_day:845, activities:['beach','food','culture'], notes:'Drive back down through Central Valley. Balboa Park, Old Town, Pacific Beach, best fish tacos in the world.', mustSee:['Balboa Park','Old Town','Coronado Island','Pacific Beach']},
  {id:'d8',  name:'Joshua Tree National Park, CA',          lat:33.8734, lng:-115.901,  days:1, hours:0, accommodation:'camping', accommodationNotes:'Campsite or Twentynine Palms motel just outside the park', budget_per_day:585, activities:['nature','adventure'], notes:'Surreal alien landscape, incredible stargazing — one of the darkest skies in the US. Late September is perfect temperature.', mustSee:['Skull Rock','Keys View','Cholla Cactus Garden','Barker Dam']},
  // ── SOUTHWEST ──
  {id:'d41', name:'Phoenix / Scottsdale, AZ',               lat:33.4484, lng:-112.0740, days:2, hours:0, accommodation:'',        accommodationNotes:'', budget_per_day:780, activities:['culture','food','nature'], notes:'Desert metropolis with great Southwestern food and Old Town Scottsdale nightlife. Camelback Mountain hike for views over the valley, Desert Botanical Garden is excellent.', mustSee:['Camelback Mountain','Old Town Scottsdale','Desert Botanical Garden']},
  {id:'d9',  name:'Sedona, AZ',                             lat:34.8697, lng:-111.7610, days:1, hours:0, accommodation:'',        accommodationNotes:'', budget_per_day:845, activities:['nature','adventure'], notes:'Oct 11–12. Red rock formations, vortexes, world-class hiking. Cathedral Rock at sunset is unreal. One night before heading to Grand Canyon.', mustSee:['Cathedral Rock','Devil\'s Bridge hike','Red Rock Crossing','Airport Mesa vortex']},
  {id:'d10', name:'Grand Canyon South Rim, AZ',             lat:36.0544, lng:-112.1401, days:2, hours:0, accommodation:'airbnb', accommodationNotes:'Book VERY early — accommodation near the rim fills months ahead. Tusayan village just outside is easier to book.', budget_per_day:780, activities:['nature','adventure'], notes:'Give yourself a full day on the rim. Mather Point at sunrise, Bright Angel Trail hike. One of the true wonders of the world.', mustSee:['Mather Point sunrise','Bright Angel Trail','Desert View Watchtower','Hermit Road sunset']},
  {id:'d11', name:'Antelope Canyon & Page, AZ',             lat:36.9147, lng:-111.4558, days:1, hours:0, accommodation:'',        accommodationNotes:'', budget_per_day:780, activities:['nature','culture'], notes:'BOOK THE ANTELOPE CANYON TOUR NOW — Upper Canyon fills months in advance. Also Horseshoe Bend is just a short walk.', mustSee:['Antelope Canyon Upper tour','Horseshoe Bend','Lake Powell viewpoint']},
  {id:'d12', name:'Monument Valley, AZ',                    lat:36.9833, lng:-110.1000, days:1, hours:0, accommodation:'',        accommodationNotes:'The View Hotel right on the rim is worth every penny — waking up to that view', budget_per_day:650, activities:['nature','culture'], notes:'The most iconic landscape in America. Drive the 17-mile Valley Loop. Hire a Navajo guide for access to restricted areas.', mustSee:['Valley Drive Loop','The Mittens at sunrise','Navajo guided tour']},
  {id:'d13', name:'Moab & Arches National Park, UT',        lat:38.5733, lng:-109.5498, days:2, hours:0, accommodation:'',        accommodationNotes:'', budget_per_day:780, activities:['nature','adventure'], notes:'Arches NP, Canyonlands, Dead Horse Point — all within 45 mins of Moab. Red rock paradise.', mustSee:['Delicate Arch hike','Dead Horse Point','Canyonlands Island in the Sky','Corona Arch']},
  {id:'d39', name:'Bryce Canyon National Park, UT',         lat:37.5931, lng:-112.1871, days:1, hours:0, accommodation:'hotel',   accommodationNotes:"Ruby's Inn — right at the park entrance, breakfast included", budget_per_day:650, activities:['nature','adventure'], notes:'Otherworldly hoodoo rock formations. Sunrise at Sunrise Point or Bryce Point is unmissable — the amphitheater glows orange and pink in the morning light. Short drive from Moab on the way to Zion.', mustSee:['Bryce Amphitheater at sunrise','Navajo Loop Trail','Sunset Point','Inspiration Point']},
  {id:'d14', name:'Zion & Orderville, UT',                  lat:37.2716, lng:-112.6385, days:2, hours:0, accommodation:'',        accommodationNotes:'Stay in Orderville (cheaper) or Springdale (inside park entrance)', budget_per_day:715, activities:['nature','adventure'], notes:'One of the best national parks in the country. The Narrows (walking up a river through a slot canyon) is unmissable. Check water levels in advance.', mustSee:['The Narrows','Angels Landing','Emerald Pools','Canyon Overlook Trail']},
  // ── ROCKIES — hitting Yellowstone in late September = perfect timing ──
  {id:'d15', name:'Salt Lake City, UT',                     lat:40.7608, lng:-111.8910, days:1, hours:0, accommodation:'',        accommodationNotes:'', budget_per_day:650, activities:['culture','food'], notes:'Good stopover night on the way north. Temple Square, the Great Salt Lake is nearby and eerily beautiful.', mustSee:['Temple Square','Great Salt Lake','Liberty Park']},
  {id:'d16', name:'Jackson Hole & Grand Teton NP, WY',      lat:43.4799, lng:-110.7624, days:2, hours:0, accommodation:'',        accommodationNotes:'', budget_per_day:1040, activities:['nature','adventure'], notes:'Late September = peak elk rut (bugling elk everywhere) + early fall colours. The Teton Range reflected in Jackson Lake is the most photogenic view in the US. Great town for food and a night out.', mustSee:['Jackson Lake reflection','Elk Refuge','Snake River overlook','Jackson town square']},
  {id:'d17', name:'Yellowstone National Park, WY',          lat:44.4280, lng:-110.5885, days:2, hours:0, accommodation:'',        accommodationNotes:'Late September = roads fully open, far fewer crowds than summer. Old Faithful Inn is spectacular if available.', budget_per_day:715, activities:['nature','adventure'], notes:'Late September is IDEAL — roads open, crowds gone, wildlife very active. Old Faithful every 90 mins, Grand Prismatic Spring from the overlook trail, bison literally walking across the road, wolves in Lamar Valley at dawn.', mustSee:['Old Faithful geyser','Grand Prismatic Spring overlook','Lamar Valley at dawn (wolves/bison)','Grand Canyon of Yellowstone']},
  {id:'d42', name:'Steamboat Springs, CO',                  lat:40.4850, lng:-106.8317, days:1, hours:0, accommodation:'',        accommodationNotes:'', budget_per_day:715, activities:['nature','adventure'], notes:'Classic Colorado ski town in the off-season — relaxed mountain vibe, hot springs to soak sore legs after Yellowstone, and a scenic drive down through the Rockies.', mustSee:['Strawberry Park Hot Springs','Downtown Steamboat Springs','Fish Creek Falls']},
  {id:'d18', name:'Denver, CO',                             lat:39.7392, lng:-104.9903, days:3, hours:0, accommodation:'',        accommodationNotes:'', budget_per_day:780, activities:['culture','nightlife','food'], notes:'Red Rocks Amphitheatre even without a concert, RiNo arts and bar district, great craft beer scene. Rocky Mountain NP is 1.5h away for a day trip.', mustSee:['Red Rocks Amphitheatre','RiNo Art District','16th Street Mall','Coors Field area']},
  {id:'d43', name:'Colorado Springs, CO',                   lat:38.8339, lng:-104.8214, days:1, hours:0, accommodation:'',        accommodationNotes:'', budget_per_day:650, activities:['nature','culture'], notes:'Garden of the Gods is a free, stunning red rock park right at the edge of the city. Pikes Peak is nearby for a scenic drive or cog railway.', mustSee:['Garden of the Gods','Pikes Peak','Manitou Springs']},
  // ── WEST TEXAS CORRIDOR ──
  {id:'d19', name:'Santa Fe, NM',                           lat:35.6870, lng:-105.9378, days:2, hours:0, accommodation:'',        accommodationNotes:'', budget_per_day:780, activities:['culture','food'], notes:'Adobe architecture, world-class art galleries, green chile on everything. The Plaza, Canyon Road galleries, Meow Wolf is a wild psychedelic art experience.', mustSee:['Canyon Road galleries','The Plaza','Meow Wolf','New Mexico Museum of Art']},
  {id:'d20', name:'Roswell, NM',                            lat:33.3943, lng:-104.5230, days:1, hours:0, accommodation:'',        accommodationNotes:'', budget_per_day:520, activities:['culture','roadtrip'], notes:'Yes the alien town — it\'s genuinely fun, a great drive break. UFO museum is cheesy in the best way. Bottomless Lakes State Park nearby is beautiful.', mustSee:['International UFO Museum','Alien-themed diners on Main St','Bottomless Lakes State Park']},
  {id:'d21', name:'El Paso, TX',                            lat:31.7619, lng:-106.4850, days:1, hours:0, accommodation:'',        accommodationNotes:'', budget_per_day:585, activities:['culture','food'], notes:'Underrated border city. Best authentic Mexican food in the US — better than most places in Mexico. Great arts district, Scenic Drive Overlook at night.', mustSee:['Scenic Drive Overlook at night','Authentic Mexican food downtown','El Paso Museum of Art']},
  {id:'d22', name:'Marfa, TX',                              lat:30.3085, lng:-104.0200, days:1, hours:0, accommodation:'airbnb', accommodationNotes:'Tiny town — book months in advance. El Cosmico (camping/trailer resort) is iconic and worth it.', budget_per_day:715, activities:['culture','adventure','roadtrip'], notes:'One of the most unique places in the US. Tiny desert art town, Donald Judd\'s massive Chinati Foundation, Prada Marfa installation on the highway, the mysterious Marfa Lights, incredible stargazing.', mustSee:['Chinati Foundation','Prada Marfa installation','Marfa Lights viewing area at dusk','El Cosmico']},
  // ── TEXAS ──
  {id:'d23', name:'Austin, TX',                             lat:30.2672, lng:-97.7431,  days:4, hours:0, accommodation:'',        accommodationNotes:'', budget_per_day:845, activities:['nightlife','food','culture'], notes:'6th Street and Rainey Street for nightlife, Barton Springs natural pool, South Congress for shopping. Live music literally everywhere every night.', mustSee:['6th Street','Barton Springs Pool','South Congress Ave','Rainey Street','Live music on every corner']},
  {id:'d24', name:'San Antonio, TX',                        lat:29.4241, lng:-98.4936,  days:1, hours:0, accommodation:'',        accommodationNotes:'', budget_per_day:650, activities:['culture','food'], notes:'The Alamo, River Walk is beautiful at night, great Mexican food and margaritas.', mustSee:['The Alamo','River Walk at night','Market Square','San Antonio missions']},
  {id:'d25', name:'Houston, TX',                            lat:29.7604, lng:-95.3698,  days:1, hours:0, accommodation:'',        accommodationNotes:'', budget_per_day:650, activities:['culture','food'], notes:'Space Center Houston is genuinely amazing — you can see actual rocket engines and mission control. Best Tex-Mex in the state in the Heights neighbourhood.', mustSee:['Space Center Houston','Museum District','The Heights neighbourhood']},
  // ── GULF COAST ──
  {id:'d26', name:'New Orleans, LA',                        lat:29.9511, lng:-90.0715,  days:5, hours:0, accommodation:'airbnb', accommodationNotes:'Book in the French Quarter or Marigny neighbourhood — walk to everything', budget_per_day:910, activities:['nightlife','food','culture'], notes:'5 nights — this city deserves it. Frenchmen Street for live jazz (NOT Bourbon Street — that\'s the tourist trap, Frenchmen is where the actual music is). Beignets at Café Du Monde at 2am. Best food city in the US. Swamp tour is a must.', mustSee:['Frenchmen Street live jazz','Café Du Monde beignets','Swamp tour','Garden District walk','Commander\'s Palace dinner']},
  {id:'d27', name:'Pensacola, FL',                          lat:30.4213, lng:-87.2169,  days:1, hours:0, accommodation:'',        accommodationNotes:'Stay near Pensacola Beach for the white sand access', budget_per_day:650, activities:['beach','nature'], notes:'Your Florida stop! Pensacola Beach has some of the whitest, finest sand in the entire US — technically it\'s quartz crystal washed down from the Appalachians, which is why it\'s so pure white. Gulf water is warm and emerald green in September/October. Pensacola also has a great historic district.', mustSee:['Pensacola Beach white sand','Gulf Islands National Seashore','Historic Pensacola Village','Fort Pickens']},
  // ── ALABAMA ──
  {id:'d28', name:'Mobile, AL',                             lat:30.6954, lng:-88.0399,  days:1, hours:0, accommodation:'',        accommodationNotes:'', budget_per_day:585, activities:['culture','food'], notes:'Underrated Southern port city, beautiful antebellum architecture, great Gulf seafood. One of the oldest cities in the US.', mustSee:['USS Alabama Battleship Memorial Park','Historic Oakleigh district','Fresh Gulf oysters downtown']},
  {id:'d29', name:'Birmingham, AL',                         lat:33.5186, lng:-86.8104,  days:1, hours:0, accommodation:'',        accommodationNotes:'', budget_per_day:618, activities:['culture','food','nightlife'], notes:'Profound Civil Rights history — the 16th Street Baptist Church and Civil Rights Institute are genuinely moving. Surprisingly great food and bar scene in Avondale neighbourhood.', mustSee:['Birmingham Civil Rights Institute','16th Street Baptist Church','Kelly Ingram Park','Avondale neighbourhood']},
  // ── TENNESSEE ──
  {id:'d30', name:'Nashville, TN',                          lat:36.1627, lng:-86.7816,  days:3, hours:0, accommodation:'',        accommodationNotes:'', budget_per_day:845, activities:['nightlife','culture','food'], notes:'3 nights — Broadway honky-tonks have free live music every single night, just walk in. Printer\'s Alley for a different vibe. Prince\'s Hot Chicken is a Nashville institution. Country Music Hall of Fame is worth half a day.', mustSee:['Broadway honky-tonks','Prince\'s Hot Chicken','Country Music Hall of Fame','Ryman Auditorium','Printer\'s Alley']},
  {id:'d31', name:'Chattanooga, TN',                        lat:35.0456, lng:-85.3097,  days:2, hours:0, accommodation:'',        accommodationNotes:'', budget_per_day:650, activities:['nature','adventure','culture'], notes:'Ruby Falls underground waterfall, Lookout Mountain with views over 7 states, great walkable riverfront downtown. Only 2h from Nashville.', mustSee:['Ruby Falls','Lookout Mountain','Tennessee Aquarium','Walnut Street Bridge']},
  // ── APPALACHIANS ──
  {id:'d32', name:'Asheville, NC',                          lat:35.5951, lng:-82.5515,  days:2, hours:0, accommodation:'',        accommodationNotes:'', budget_per_day:780, activities:['food','culture','nature'], notes:'Best food scene in the South after New Orleans. Blue Ridge Parkway in October = absolute peak fall colours, one of the great drives in America. Biltmore Estate is America\'s largest private home — worth the ticket.', mustSee:['Blue Ridge Parkway fall foliage','Biltmore Estate','River Arts District','Downtown restaurants']},
  {id:'d33', name:'Pigeon Forge & Great Smoky Mountains, TN', lat:35.7884, lng:-83.5543, days:1, hours:0, accommodation:'airbnb', accommodationNotes:'Rent a mountain cabin — they\'re everywhere, great value for 3 people, cosy for October', budget_per_day:650, activities:['nature','adventure'], notes:'Great Smoky Mountains NP in October = peak fall foliage, most beautiful in the eastern US. Clingmans Dome for 360° views. Cades Cove wildlife loop at sunrise for deer and black bears.', mustSee:['Clingmans Dome','Cades Cove loop at sunrise','Laurel Falls','Alum Cave Trail']},
  // ── CAROLINA COAST ──
  {id:'d34', name:'Savannah, GA',                           lat:32.0835, lng:-81.0998,  days:2, hours:0, accommodation:'',        accommodationNotes:'Stay near Forsyth Park in the historic district — walk everywhere', budget_per_day:715, activities:['culture','food','nightlife'], notes:'One of the most beautiful cities in the US and criminally underrated. Spanish moss draped over squares, gorgeous antebellum architecture, incredible food scene, lively bar strip on River Street. Very walkable.', mustSee:['Forsyth Park','River Street','Bonaventure Cemetery','City Market','Forsyth Park farmers market']},
  {id:'d35', name:'Charleston, SC',                         lat:32.7765, lng:-79.9311,  days:1, hours:0, accommodation:'',        accommodationNotes:'Stay downtown near the historic district', budget_per_day:780, activities:['culture','food','beach'], notes:'Rainbow Row (pastel-coloured houses) is iconic, the food scene rivals anywhere in the South, Sullivan\'s Island and Folly Beach nearby for a beach afternoon. Very different vibe from Savannah but equally beautiful.', mustSee:['Rainbow Row','The Battery waterfront','King Street food & bars','Sullivan\'s Island beach','Fort Sumter ferry']},
  {id:'d44', name:'Richmond, VA',                           lat:37.5407, lng:-77.4360,  days:1, hours:0, accommodation:'',        accommodationNotes:'', budget_per_day:715, activities:['culture','food'], notes:'Capital of Virginia with a rich and complex history — Civil War sites, the Virginia State Capitol, and a surprisingly great food and craft beer scene along the James River.', mustSee:['Virginia State Capitol','Belle Isle & James River','Carytown']},
  // ── EAST COAST ──
  {id:'d36', name:'Washington D.C.',                        lat:38.9072, lng:-77.0369,  days:4, hours:0, accommodation:'',        accommodationNotes:'Stay in Capitol Hill or Logan Circle — good access, walkable', budget_per_day:910, activities:['culture','food'], notes:'Every Smithsonian museum is completely free — the Air & Space Museum, Natural History, American History. Lincoln Memorial at night is genuinely one of the most powerful experiences in the US. Georgetown for dinner.', mustSee:['Lincoln Memorial at night','Smithsonian Air & Space Museum','Capitol Hill','Georgetown dinner','Vietnam Veterans Memorial']},
  {id:'d37', name:'Philadelphia, PA',                       lat:39.9526, lng:-75.1652,  days:2, hours:0, accommodation:'',        accommodationNotes:'', budget_per_day:780, activities:['culture','food'], notes:'Liberty Bell, Reading Terminal Market (best food market on the East Coast), a proper Philly cheesesteak at Pat\'s or Geno\'s. Easy Amtrak from D.C.', mustSee:['Liberty Bell & Independence Hall','Reading Terminal Market','Philly cheesesteak at Pat\'s vs Geno\'s','Old City']},
  {id:'d38', name:'New York City & Clark, NJ',              lat:40.7128, lng:-74.0060,  days:7, hours:0, accommodation:'friends', accommodationNotes:'Staying with friend\'s uncle in Clark, NJ — free accommodation! NJ Transit train to Penn Station takes ~45 mins and runs all day. Newark Airport (EWR) is only 15 mins from Clark — your flight home.', budget_per_day:780, activities:['culture','nightlife','food','shopping'], notes:'7 nights based in Clark, NJ — commuting into Manhattan daily by train which is very doable and how millions of New Yorkers actually live. Budget is lower than usual since accommodation is free. Brooklyn Bridge walk at sunrise, Central Park, a Broadway show, East Village nightlife, pizza at 3am, High Line, one day in Brooklyn. Flying home from Newark (EWR) — SAS direct to CPH.', mustSee:['Brooklyn Bridge at sunrise','Central Park','Broadway show','High Line','East Village','One World Trade Observatory','Coney Island','Staten Island Ferry (free, great Statue of Liberty view)']},
];

export const BUDGET_FIXED = [
  {id:'f1', label:'✈️ Flight CPH → SFO (Sep 21)', estimated:5200, actual:null, notes:'SAS direct ~11h. Book asap — September is busier than October'},
  {id:'f2', label:'✈️ Flight EWR → CPH (~Dec 14)', estimated:3250, actual:null, notes:'SAS direct ~7h50m from Newark — December is low season, good prices'},
  {id:'f3', label:'🛂 ESTA (per person)', estimated:262, actual:null, notes:'Apply at esta.cbp.dhs.gov — takes up to 72h, do it weeks before'},
  {id:'f4', label:'🏞️ National Parks Pass', estimated:1625, actual:null, notes:'$250 non-resident pass — covers Yosemite, Grand Canyon, Zion, Arches, Yellowstone, Grand Teton + more'},
  {id:'f5', label:'🚗 Car purchase (÷3)', estimated:6933, actual:null, notes:'$3,200 total ÷ 3 people = $1,067/person. Buy in SF, sell in NJ.'},
  {id:'f6', label:'⛽ Gas estimate (÷3)', estimated:3770, actual:null, notes:'~9,500mi route, 30mpg, ~$4.80/gal avg incl. California premium. 20% buffer included.'},
  {id:'f7', label:'🛡️ Travel insurance', estimated:1300, actual:null, notes:'90 days in US — medical costs without insurance can be catastrophic'},
];

export const CITIES = [
  {name:'San Francisco, CA',lat:37.7749,lng:-122.4194},
  {name:'Los Angeles, CA',lat:34.0522,lng:-118.2437},
  {name:'San Diego, CA',lat:32.7157,lng:-117.1611},
  {name:'Sacramento, CA',lat:38.5816,lng:-121.4944},
  {name:'Monterey, CA',lat:36.6002,lng:-121.8947},
  {name:'Big Sur, CA',lat:36.2704,lng:-121.8081},
  {name:'San Luis Obispo, CA',lat:35.2828,lng:-120.6596},
  {name:'Santa Barbara, CA',lat:34.4208,lng:-119.6982},
  {name:'Napa Valley, CA',lat:38.2975,lng:-122.2869},
  {name:'Palm Springs, CA',lat:33.8303,lng:-116.5453},
  {name:'Yosemite National Park, CA',lat:37.8651,lng:-119.5383},
  {name:'Death Valley National Park, CA',lat:36.5054,lng:-117.0794},
  {name:'Joshua Tree National Park, CA',lat:33.8734,lng:-115.901},
  {name:'Sequoia National Park, CA',lat:36.4864,lng:-118.5658},
  {name:'Lake Tahoe, CA',lat:39.0968,lng:-120.0324},
  {name:'Mammoth Lakes, CA',lat:37.6485,lng:-118.9721},
  {name:'Las Vegas, NV',lat:36.1699,lng:-115.1398},
  {name:'Reno, NV',lat:39.5296,lng:-119.8138},
  {name:'Phoenix, AZ',lat:33.4484,lng:-112.074},
  {name:'Tucson, AZ',lat:32.2226,lng:-110.9747},
  {name:'Scottsdale, AZ',lat:33.4942,lng:-111.9261},
  {name:'Flagstaff, AZ',lat:35.1983,lng:-111.6513},
  {name:'Sedona, AZ',lat:34.8697,lng:-111.761},
  {name:'Grand Canyon South Rim, AZ',lat:36.0544,lng:-112.1401},
  {name:'Grand Canyon North Rim, AZ',lat:36.2079,lng:-112.0539},
  {name:'Antelope Canyon & Page, AZ',lat:36.9147,lng:-111.4558},
  {name:'Monument Valley, AZ',lat:36.9833,lng:-110.1},
  {name:'Horseshoe Bend, AZ',lat:36.8791,lng:-111.5105},
  {name:'Jerome, AZ',lat:34.7487,lng:-112.1138},
  {name:'Bisbee, AZ',lat:31.4479,lng:-109.9281},
  {name:'Salt Lake City, UT',lat:40.7608,lng:-111.891},
  {name:'Moab, UT',lat:38.5733,lng:-109.5498},
  {name:'St. George, UT',lat:37.0965,lng:-113.5684},
  {name:'Park City, UT',lat:40.6461,lng:-111.498},
  {name:'Zion National Park, UT',lat:37.2982,lng:-113.0263},
  {name:'Bryce Canyon National Park, UT',lat:37.5931,lng:-112.1871},
  {name:'Arches National Park, UT',lat:38.7331,lng:-109.5925},
  {name:'Canyonlands National Park, UT',lat:38.3269,lng:-109.8783},
  {name:'Orderville, UT',lat:37.2716,lng:-112.6385},
  {name:'Kanab, UT',lat:37.0474,lng:-112.5263},
  {name:'Capitol Reef National Park, UT',lat:38.0877,lng:-111.1478},
  {name:'Dead Horse Point, UT',lat:38.4831,lng:-109.7395},
  {name:'Denver, CO',lat:39.7392,lng:-104.9903},
  {name:'Colorado Springs, CO',lat:38.8339,lng:-104.8214},
  {name:'Boulder, CO',lat:40.015,lng:-105.2705},
  {name:'Aspen, CO',lat:39.1911,lng:-106.8175},
  {name:'Vail, CO',lat:39.6433,lng:-106.3781},
  {name:'Telluride, CO',lat:37.9375,lng:-107.8123},
  {name:'Durango, CO',lat:37.2753,lng:-107.8801},
  {name:'Rocky Mountain National Park, CO',lat:40.3428,lng:-105.6836},
  {name:'Mesa Verde National Park, CO',lat:37.1853,lng:-108.4862},
  {name:'Garden of the Gods, CO',lat:38.8734,lng:-104.8864},
  {name:'Estes Park, CO',lat:40.3772,lng:-105.5217},
  {name:'Yellowstone National Park, WY',lat:44.428,lng:-110.5885},
  {name:'Grand Teton National Park, WY',lat:43.7904,lng:-110.6818},
  {name:'Jackson Hole, WY',lat:43.4799,lng:-110.7624},
  {name:'Cody, WY',lat:44.5263,lng:-109.0565},
  {name:'Cheyenne, WY',lat:41.14,lng:-104.8202},
  {name:'Devils Tower, WY',lat:44.5904,lng:-104.7146},
  {name:'Glacier National Park, MT',lat:48.7596,lng:-113.787},
  {name:'Billings, MT',lat:45.7833,lng:-108.5007},
  {name:'Bozeman, MT',lat:45.677,lng:-111.0429},
  {name:'Boise, ID',lat:43.615,lng:-116.2023},
  {name:'Sun Valley, ID',lat:43.6969,lng:-114.3514},
  {name:'Seattle, WA',lat:47.6062,lng:-122.3321},
  {name:'Portland, OR',lat:45.5152,lng:-122.6784},
  {name:'Bend, OR',lat:44.0582,lng:-121.3153},
  {name:'Crater Lake National Park, OR',lat:42.9446,lng:-122.109},
  {name:'Cannon Beach, OR',lat:45.8918,lng:-123.9615},
  {name:'Albuquerque, NM',lat:35.0844,lng:-106.6504},
  {name:'Santa Fe, NM',lat:35.687,lng:-105.9378},
  {name:'Taos, NM',lat:36.4072,lng:-105.5731},
  {name:'Roswell, NM',lat:33.3943,lng:-104.523},
  {name:'White Sands National Park, NM',lat:32.7872,lng:-106.3258},
  {name:'Carlsbad Caverns, NM',lat:32.1479,lng:-104.5567},
  {name:'Houston, TX',lat:29.7604,lng:-95.3698},
  {name:'San Antonio, TX',lat:29.4241,lng:-98.4936},
  {name:'Dallas, TX',lat:32.7767,lng:-96.797},
  {name:'Austin, TX',lat:30.2672,lng:-97.7431},
  {name:'El Paso, TX',lat:31.7619,lng:-106.485},
  {name:'Amarillo, TX',lat:35.222,lng:-101.8313},
  {name:'Marfa, TX',lat:30.3085,lng:-104.02},
  {name:'Big Bend National Park, TX',lat:29.1275,lng:-103.2425},
  {name:'Fredericksburg, TX',lat:30.2752,lng:-98.872},
  {name:'Galveston, TX',lat:29.2988,lng:-94.7977},
  {name:'New Orleans, LA',lat:29.9511,lng:-90.0715},
  {name:'Baton Rouge, LA',lat:30.4515,lng:-91.1871},
  {name:'Lafayette, LA',lat:30.2241,lng:-92.0198},
  {name:'Mobile, AL',lat:30.6954,lng:-88.0399},
  {name:'Birmingham, AL',lat:33.5186,lng:-86.8104},
  {name:'Montgomery, AL',lat:32.3668,lng:-86.3},
  {name:'Huntsville, AL',lat:34.7304,lng:-86.5861},
  {name:'Gulf Shores, AL',lat:30.246,lng:-87.7008},
  {name:'Nashville, TN',lat:36.1627,lng:-86.7816},
  {name:'Memphis, TN',lat:35.1495,lng:-90.049},
  {name:'Knoxville, TN',lat:35.9606,lng:-83.9207},
  {name:'Chattanooga, TN',lat:35.0456,lng:-85.3097},
  {name:'Pigeon Forge, TN',lat:35.7884,lng:-83.5543},
  {name:'Gatlinburg, TN',lat:35.7143,lng:-83.5118},
  {name:'Great Smoky Mountains NP, TN',lat:35.6532,lng:-83.5074},
  {name:'Atlanta, GA',lat:33.749,lng:-84.388},
  {name:'Savannah, GA',lat:32.0835,lng:-81.0998},
  {name:'Jacksonville, FL',lat:30.3322,lng:-81.6557},
  {name:'Miami, FL',lat:25.7617,lng:-80.1918},
  {name:'Orlando, FL',lat:28.5383,lng:-81.3792},
  {name:'Tampa, FL',lat:27.9506,lng:-82.4572},
  {name:'Key West, FL',lat:24.5551,lng:-81.78},
  {name:'Charleston, SC',lat:32.7765,lng:-79.9311},
  {name:'Myrtle Beach, SC',lat:33.6891,lng:-78.8867},
  {name:'Charlotte, NC',lat:35.2271,lng:-80.8431},
  {name:'Raleigh, NC',lat:35.7796,lng:-78.6382},
  {name:'Asheville, NC',lat:35.5951,lng:-82.5515},
  {name:'Outer Banks, NC',lat:35.5585,lng:-75.4665},
  {name:'Virginia Beach, VA',lat:36.8529,lng:-75.978},
  {name:'Richmond, VA',lat:37.5407,lng:-77.436},
  {name:'Shenandoah National Park, VA',lat:38.4755,lng:-78.4535},
  {name:'Washington D.C.',lat:38.9072,lng:-77.0369},
  {name:'Baltimore, MD',lat:39.2904,lng:-76.6122},
  {name:'Annapolis, MD',lat:38.9784,lng:-76.4922},
  {name:'Philadelphia, PA',lat:39.9526,lng:-75.1652},
  {name:'Pittsburgh, PA',lat:40.4406,lng:-79.9959},
  {name:'Gettysburg, PA',lat:39.8309,lng:-77.2311},
  {name:'New York City, NY',lat:40.7128,lng:-74.006},
  {name:'Clark, NJ',lat:40.6368,lng:-74.3132},
  {name:'Atlantic City, NJ',lat:39.3643,lng:-74.4229},
  {name:'Cape May, NJ',lat:38.9351,lng:-74.906},
  {name:'Boston, MA',lat:42.3601,lng:-71.0589},
  {name:'Cape Cod, MA',lat:41.6688,lng:-70.2962},
  {name:'Salem, MA',lat:42.5195,lng:-70.8967},
  {name:'Newport, RI',lat:41.4901,lng:-71.3128},
  {name:'Providence, RI',lat:41.824,lng:-71.4128},
  {name:'Portland, ME',lat:43.6591,lng:-70.2568},
  {name:'Bar Harbor, ME',lat:44.3876,lng:-68.2039},
  {name:'Acadia National Park, ME',lat:44.3386,lng:-68.2733},
  {name:'Burlington, VT',lat:44.4759,lng:-73.2121},
  {name:'Stowe, VT',lat:44.4654,lng:-72.6874},
  {name:'Chicago, IL',lat:41.8781,lng:-87.6298},
  {name:'St. Louis, MO',lat:38.627,lng:-90.1994},
  {name:'Kansas City, MO',lat:39.0997,lng:-94.5786},
  {name:'Minneapolis, MN',lat:44.9778,lng:-93.265},
  {name:'Detroit, MI',lat:42.3314,lng:-83.0458},
  {name:'Cleveland, OH',lat:41.4993,lng:-81.6944},
  {name:'Columbus, OH',lat:39.9612,lng:-82.9988},
  {name:'Indianapolis, IN',lat:39.7684,lng:-86.1581},
  {name:'Louisville, KY',lat:38.2527,lng:-85.7585},
  {name:'Mammoth Cave NP, KY',lat:37.1862,lng:-86.1003},
  {name:'Mount Rushmore, SD',lat:43.8791,lng:-103.4591},
  {name:'Badlands National Park, SD',lat:43.8554,lng:-102.3397},
  {name:'Rapid City, SD',lat:44.0805,lng:-103.231},
];

// Wikipedia page title for each stop's most iconic landmark — used to fetch a background photo
export const LANDMARKS = {
  d1:  'Golden Gate Bridge',
  d2:  'Monterey Bay Aquarium',
  d3:  'Bixby Creek Bridge',
  d4:  'Madonna Inn',
  d5:  'Hollywood Sign',
  d6:  'Half Dome',
  d7:  'Balboa Park (San Diego)',
  d8:  'Joshua Tree National Park',
  d9:  'Cathedral Rock (Sedona, Arizona)',
  d10: 'Grand Canyon',
  d11: 'Antelope Canyon',
  d12: 'Monument Valley',
  d13: 'Delicate Arch',
  d14: 'Zion National Park',
  d15: 'Temple Square',
  d16: 'Grand Teton',
  d17: 'Old Faithful',
  d18: 'Red Rocks Amphitheatre',
  d19: 'Santa Fe Plaza',
  d20: 'International UFO Museum and Research Center',
  d21: 'Franklin Mountains State Park',
  d22: 'Prada Marfa',
  d23: 'Texas State Capitol',
  d24: 'Alamo Mission in San Antonio',
  d25: 'Space Center Houston',
  d26: 'French Quarter',
  d27: 'Pensacola Beach',
  d28: 'USS Alabama (BB-60)',
  d29: 'Birmingham Civil Rights Institute',
  d30: 'Ryman Auditorium',
  d31: 'Lookout Mountain (Tennessee)',
  d32: 'Biltmore Estate',
  d33: 'Great Smoky Mountains National Park',
  d34: 'Forsyth Park',
  d35: 'Rainbow Row',
  d36: 'Lincoln Memorial',
  d37: 'Liberty Bell',
  d38: 'Brooklyn Bridge',
  d39: 'Bryce Canyon National Park',
  d40: 'Santa Barbara Mission',
  d41: 'Camelback Mountain',
  d42: 'Steamboat Ski Resort',
  d43: 'Garden of the Gods',
  d44: 'Virginia State Capitol',
};

// Bookings migrated from roadtrip-bookings.html (Supabase trip_bookings table), mapped to route stops
export const SEED_BOOKINGS = {
  d6: [
    {id:'b1780758034426', stopId:'d6', type:'hotel', status:'booked', name:'The Yosemite Inn', date:'2026-09-24', time:'', confirmRef:'30317', price:2118, notes:'Standard Double Queen · Mariposa, CA · Check-out 26 Sep 2026', paidBy:'Andreas'},
  ],
  d8: [
    {id:'b_motel6_twentynine', stopId:'d8', type:'hotel', status:'booked', name:'Motel 6 Twentynine Palms', date:'2026-10-08', time:'', confirmRef:'VMWOQQKBK6', price:443, notes:'2 Queen Beds, Mini Fridge. 72562 Twentynine Palms Highway CA 92277. Tel: 760-904-6992. Promo code MY6DEAL used. Check-out 9 Oct 2026. Check cancellation policy on booking.', paidBy:'Andreas'},
  ],
  d10: [
    {id:'b1780758128807', stopId:'d10', type:'hotel', status:'booked', name:'Grand Canyon Plaza Hotel', date:'2026-10-12', time:'', confirmRef:'1076141340', price:3329, notes:'Deluxe Double · Check-out 14 Oct 2026', paidBy:'Andreas'},
  ],
  d11: [
    {id:'b_rodeway_page', stopId:'d11', type:'hotel', status:'booked', name:'Rodeway Inn at Lake Powell', date:'2026-10-14', time:'', confirmRef:'40850224', price:541, notes:'2 Queen Beds No Smoking, 3 occupants. Check-in 15:00, check-out 11:00. $100 deposit required on arrival (no cash). 107 South Lake Powell Blvd, Page AZ 86040. Tel: +1 928-378-1462. Check-out 15 Oct 2026. No cancellations, changes, or refunds.', paidBy:'Andreas'},
  ],
  d12: [
    {id:'b1780757958594', stopId:'d12', type:'hotel', status:'booked', name:'Wetherill Inn', date:'2026-10-15', time:'', confirmRef:'WIAZ05244441', price:1353, notes:'2 Queen Non Smoking · Check-out 16 Oct 2026 · Free cancellation 48 hours before', paidBy:'Andreas'},
  ],
  d13: [
    {id:'b_inca_inn_moab', stopId:'d13', type:'hotel', status:'booked', name:'Inca Inn', date:'2026-10-16', time:'', confirmRef:'0470ACT554', price:2538, notes:'Double Queen Premium room, 2 nights, 3 guests. 570 N Main St, Moab UT 84532. Tel: 435-259-7261. reservations@incainn.com. Check-out 18 Oct 2026.', paidBy:'Andreas'},
  ],
  d39: [
    {id:'b_rubys_inn_bryce', stopId:'d39', type:'hotel', status:'booked', name:"Ruby's Inn (Bryce Canyon)", date:'2026-10-18', time:'', confirmRef:'534725145', price:1215, notes:'2 Queen Beds Non-Smoking, breakfast included, 3 adults. Check-in 16:00, check-out 11:00. 26 South Main Street, Bryce Canyon City. Tel: (435) 834-5341. Check-out 19 Oct 2026. Free cancellation until 18 Oct 2026 16:00 local time.', paidBy:'Andreas'},
  ],
  d14: [
    {id:'b_bestwes_zion', stopId:'d14', type:'hotel', status:'booked', name:'Best Western East Zion Thunderbird Lodge', date:'2026-10-19', time:'', confirmRef:'796725148', price:1971, notes:'2 Queen Beds, Non-Smoking, Microwave & Fridge, Wi-Fi. 2 nights, 3 adults. 4530 State Street, Mount Carmel UT 84755. Tel: (435) 648-2203. Check-in 16:00, check-out 11:00. Check-out 21 Oct 2026. Pay on arrival — $0 charged today.', paidBy:'Andreas'},
  ],
  d16: [
    {id:'b_jackson_southtown', stopId:'d16', type:'hotel', status:'booked', name:'The Jackson Southtown', date:'2026-10-22', time:'', confirmRef:'0744AEL315', price:3263, notes:'Full Bunk Studio, max occupancy 4, 2 nights, 3 guests. 600 US-89, Jackson WY 83001. Tel: 307-733-1620. frontjackson@mogulcapital.com. Check-out 24 Oct 2026.', paidBy:'Andreas'},
  ],
  d17: [
    {id:'b_graywolf_yellowstone', stopId:'d17', type:'hotel', status:'booked', name:'Gray Wolf Inn & Suites', date:'2026-10-24', time:'', confirmRef:'28577SG163120', price:1768, notes:'Deluxe Room 2 Queens. 2 nights at $136/night + tax. Check-in 16:00, check-out 11:00, all rooms non-smoking. Check-out 26 Oct 2026. Non-refundable — full payment taken at booking.', paidBy:'Andreas'},
  ],
};
